import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/contexts/authContext";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId={GOOGLE_CLIENT_ID}>
          <AuthContextProvider>{children}</AuthContextProvider>
          <Toaster position="bottom-right" />
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
